"""
report/pdf_generator.py — Professional PDF report generator using fpdf2
"""

import os
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any, Optional
from loguru import logger
from fpdf import FPDF
from PIL import Image as PILImage

from config import REPORT_DIR, BRAND_COLORS
from graph.state import FinancialAgentState, AgentMessage


# ─── Custom FPDF class ────────────────────────────────────────────────────────
class FinancialReportPDF(FPDF):

    def __init__(self, ticker: str, company_name: str):
        super().__init__("P", "mm", "A4")
        self.ticker = ticker
        self.company_name = company_name
        self.set_margins(18, 18, 18)

    def _clean(self, text: Any) -> str:
        """Sanitise text for Helvetica (Latin-1) by replacing common Unicode chars or stripping them."""
        if text is None:
            return ""
        s = str(text)
        # Replace common financial symbols FPDF Helvetica can't handle
        replacements = {
            "📈": "[Bullish]", "📉": "[Bearish]", "↔": "[Sideways]",
            "🟢": "(+)", "🔴": "(-)", "⚪": "(?)", "🟡": "(~)",
            "🚀": "[Catalyst]", "⚠️": "[Risk]", "💰": "[Fin]",
            "📐": "[KPI]", "📊": "[Chart]", "📰": "[News]",
            "🏁": "[Done]", "✅": "[OK]", "🤖": "[AI]",
            "✍️": "[Drafting]", "🔍": "[Search]", "📑": "[Report]",
            "📄": "[PDF]", "📥": "[Download]", "📐": "[Alt]", "📐": "[KPI]",
        }
        for char, sub in replacements.items():
            s = s.replace(char, sub)
        # Final fallback: encode to latin-1 and replace unknown chars with ?
        try:
            return s.encode("latin-1", "replace").decode("latin-1")
        except Exception:
            return s.encode("ascii", "ignore").decode("ascii")

    def header(self):
        # Header bar
        self.set_fill_color(108, 62, 244)  # primary purple
        self.rect(0, 0, 210, 14, "F")
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 3)
        header_title = self._clean(f"FINANCIAL ANALYSIS REPORT  |  {self.company_name} ({self.ticker})")
        self.cell(0, 8, header_title, align="L")
        self.set_xy(0, 3)
        self.cell(200, 8, datetime.now().strftime("%B %d, %Y"), align="R")
        self.ln(10)

    def footer(self):
        self.set_y(-14)
        self.set_fill_color(26, 26, 46)
        self.rect(0, self.get_y(), 210, 14, "F")
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(160, 160, 180)
        self.cell(0, 8, "This report is generated by AI and is for informational purposes only. "
                        "Not financial advice. Past performance does not guarantee future results.", align="C")
        self.set_xy(160, self.get_y())
        self.cell(40, 8, f"Page {self.page_no()}", align="R")

    def section_title(self, title: str, color=(108, 62, 244)):
        self.ln(4)
        self.set_fill_color(*color)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, f"  {self._clean(title)}", fill=True, ln=True)
        self.set_text_color(40, 40, 60)
        self.ln(2)

    def body_text(self, text: str, font_size: int = 9):
        self.set_font("Helvetica", "", font_size)
        self.set_text_color(45, 55, 72)
        self.multi_cell(0, 5, self._clean(text))
        self.ln(2)

    def kv_row(self, label: str, value: str, signal: str = "", alt: bool = False):
        fill_color = (240, 244, 255) if alt else (255, 255, 255)
        self.set_fill_color(*fill_color)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(80, 80, 100)
        self.cell(65, 6, f"  {self._clean(label)}", fill=True)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(30, 30, 50)
        self.cell(50, 6, self._clean(str(value)), fill=True)
        if signal:
            if "🟢" in signal or "Strong" in signal or "Positive" in signal or "Above" in signal:
                self.set_text_color(22, 163, 74)
            elif "🔴" in signal or "Risk" in signal or "Negative" in signal or "Below" in signal:
                self.set_text_color(220, 38, 38)
            else:
                self.set_text_color(100, 100, 120)
            self.set_font("Helvetica", "I", 8)
            self.cell(0, 6, self._clean(signal), fill=True)
        self.ln(6)

    def insert_chart(self, path: str, w: int = 174, caption: str = ""):
        if not path or not Path(path).exists():
            return
        try:
            self.image(path, x=18, w=w)
            if caption:
                self.set_font("Helvetica", "I", 7)
                self.set_text_color(120, 120, 140)
                self.cell(0, 5, self._clean(caption), align="C", ln=True)
            self.ln(3)
        except Exception as e:
            logger.warning(f"Could not insert chart {path}: {e}")

    def rec_badge(self, recommendation: str):
        color_map = {
            "BUY":  (22, 163, 74),
            "HOLD": (245, 158, 11),
            "SELL": (220, 38, 38),
        }
        color = color_map.get(recommendation.upper(), (100, 100, 120))
        self.set_fill_color(*color)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 18)
        self.cell(50, 14, f" {recommendation.upper()} ", fill=True, align="C")


# ─── Main generator function ──────────────────────────────────────────────────
def generate_pdf(state: FinancialAgentState) -> str:
    ticker = state["ticker"]
    company_name = state.get("company_name", ticker)
    stock_data = state.get("stock_data") or {}
    news_data = state.get("news_data") or {}
    analysis_data = state.get("analysis_data") or {}
    report_data = state.get("report_data") or {}
    messages = state.get("messages", [])

    pdf = FinancialReportPDF(ticker, company_name)

    # ── PAGE 1: Cover ──────────────────────────────────────────
    pdf.add_page()
    _page_cover(pdf, ticker, company_name, stock_data, report_data)

    # ── PAGE 2: Executive Summary + Market Overview ────────────
    pdf.add_page()
    _page_summary(pdf, stock_data, report_data, news_data, analysis_data)

    # ── PAGE 3: Price Chart + Returns ─────────────────────────
    chart_paths = analysis_data.get("chart_paths", [])
    if chart_paths:
        pdf.add_page()
        _page_charts(pdf, chart_paths, ticker)

    # ── PAGE 4: KPI Table ─────────────────────────────────────
    pdf.add_page()
    _page_kpis(pdf, analysis_data.get("kpi_table", []), ticker)

    # ── PAGE 5: Market Research + Sentiment ───────────────────
    pdf.add_page()
    _page_research(pdf, report_data, news_data, chart_paths)

    # ── PAGE 6: Recommendation ────────────────────────────────
    pdf.add_page()
    _page_recommendation(pdf, report_data, stock_data, analysis_data)

    # ── PAGE 7: Agent Conversation Log ────────────────────────
    if messages:
        pdf.add_page()
        _page_agent_log(pdf, messages)

    # ── Save ───────────────────────────────────────────────────
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = REPORT_DIR / f"{ticker}_analysis_{ts}.pdf"
    pdf.output(str(out_path))
    logger.info(f"PDF saved: {out_path}")
    return str(out_path)


# ─── Page builders ────────────────────────────────────────────────────────────

def _page_cover(pdf, ticker, company_name, stock_data, report_data):
    # Purple gradient bar at top
    pdf.set_fill_color(108, 62, 244)
    pdf.rect(0, 14, 210, 60, "F")

    pdf.set_xy(18, 22)
    pdf.set_font("Helvetica", "B", 26)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 12, company_name, ln=True)

    pdf.set_x(18)
    pdf.set_font("Helvetica", "", 13)
    pdf.cell(0, 8, f"Ticker: {ticker}  |  Sector: {stock_data.get('sector','N/A')}  |  "
                   f"Industry: {stock_data.get('industry','N/A')}", ln=True)

    pdf.set_x(18)
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(200, 200, 220)
    pdf.cell(0, 7, f"Report Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}", ln=True)

    # Quick stats row
    pdf.ln(16)
    price = stock_data.get("current_price", "N/A")
    chg = stock_data.get("price_change_pct", 0)
    mc = stock_data.get("market_cap") or 0
    hi52 = stock_data.get("fifty_two_week_high", "N/A")
    lo52 = stock_data.get("fifty_two_week_low", "N/A")

    stats = [
        ("Current Price", f"${price}"),
        ("Today's Change", f"{chg:+.2f}%"),
        ("Market Cap", f"${mc/1e9:.2f}B" if mc else "N/A"),
        ("52W High", f"${hi52}"),
        ("52W Low", f"${lo52}"),
    ]
    _stat_boxes(pdf, stats)

    # Recommendation badge
    pdf.ln(10)
    rec = report_data.get("recommendation", "HOLD")
    conf = report_data.get("confidence_score", 50)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(40, 40, 60)
    pdf.cell(0, 8, "AI Investment Recommendation:", ln=True)
    pdf.ln(2)
    pdf.rec_badge(rec)
    pdf.set_x(80)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 100)
    pdf.cell(0, 14, f"  Confidence: {conf:.0f}%  |  "
                    f"Target: ${report_data.get('target_price','N/A')}", align="L")
    pdf.ln(8)

    # Description
    desc = stock_data.get("description", "")[:500]
    if desc:
        pdf.section_title("Company Overview")
        pdf.body_text(desc)


def _stat_boxes(pdf, stats):
    box_w = (210 - 36) / len(stats)
    x0 = 18
    for label, value in stats:
        pdf.set_xy(x0, pdf.get_y())
        pdf.set_fill_color(240, 236, 255)
        pdf.rect(x0, pdf.get_y(), box_w - 2, 18, "F")
        pdf.set_xy(x0 + 1, pdf.get_y() + 2)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(108, 62, 244)
        pdf.cell(box_w - 4, 4, label, ln=True)
        pdf.set_x(x0 + 1)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 60)
        pdf.cell(box_w - 4, 7, str(value))
        x0 += box_w
    pdf.ln(20)


def _page_summary(pdf, stock_data, report_data, news_data, analysis_data):
    pdf.section_title("Executive Summary")
    pdf.body_text(report_data.get("executive_summary", ""))

    pdf.section_title("Key Financial Metrics", color=(0, 160, 120))
    kpis_display = [
        ("Current Price",      f"${stock_data.get('current_price','N/A')}",
         f"Change: {stock_data.get('price_change_pct',0):+.2f}%"),
        ("Market Cap",         f"${(stock_data.get('market_cap') or 0)/1e9:.2f}B", ""),
        ("Price Trend",        analysis_data.get("price_trend","N/A"), ""),
        ("Volatility",         analysis_data.get("volatility_level","N/A"), ""),
        ("Fundamental Score",  f"{analysis_data.get('fundamental_score',0):.0f}/100", ""),
        ("News Sentiment",     news_data.get("sentiment_label","N/A"), ""),
        ("Recommendation",     report_data.get("recommendation","HOLD"),
         f"Confidence: {report_data.get('confidence_score',50):.0f}%"),
    ]
    for i, (label, val, sig) in enumerate(kpis_display):
        pdf.kv_row(label, val, sig, alt=(i % 2 == 0))


def _page_charts(pdf, chart_paths, ticker):
    pdf.section_title("Price History & Technical Charts")
    for i, path in enumerate(chart_paths[:3]):
        if path and Path(path).exists():
            caption = ["Price history with moving averages and volume",
                       "KPI fundamental signals", "Daily returns distribution"][i] if i < 3 else ""
            pdf.insert_chart(path, caption=caption)
            if i < 2 and pdf.get_y() > 200:
                pdf.add_page()


def _page_kpis(pdf, kpi_table, ticker):
    pdf.section_title("Detailed KPI Analysis")

    if not kpi_table:
        pdf.body_text("KPI data unavailable.")
        return

    # Table header
    pdf.set_fill_color(108, 62, 244)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(35, 7, "  Category", fill=True)
    pdf.cell(50, 7, "Metric", fill=True)
    pdf.cell(35, 7, "Value", fill=True)
    pdf.cell(0, 7, "Signal", fill=True)
    pdf.ln(7)

    for i, kpi in enumerate(kpi_table):
        bg = (248, 246, 255) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)
        pdf.set_text_color(80, 80, 100)
        pdf.set_font("Helvetica", "", 8)
        pdf.cell(35, 6, f"  {pdf._clean(kpi.get('category',''))}", fill=True)
        pdf.cell(50, 6, pdf._clean(kpi.get("metric", "")), fill=True)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(30, 30, 60)
        pdf.cell(35, 6, pdf._clean(kpi.get("value", "")), fill=True)

        signal = kpi.get("signal", "")
        if "🟢" in signal or "Positive" in signal or "Strong" in signal or "Above" in signal:
            pdf.set_text_color(22, 163, 74)
        elif "🔴" in signal or "Negative" in signal or "Risky" in signal or "Below" in signal:
            pdf.set_text_color(220, 38, 38)
        else:
            pdf.set_text_color(100, 100, 120)
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 6, pdf._clean(signal), fill=True)
        pdf.ln(6)

        if pdf.get_y() > 265:
            pdf.add_page()
            pdf.section_title("Detailed KPI Analysis (continued)")


def _page_research(pdf, report_data, news_data, chart_paths):
    pdf.section_title("Market Research & Sentiment Analysis")
    pdf.body_text(report_data.get("market_research_section", ""))

    # Sentiment chart
    if len(chart_paths) > 3 and Path(chart_paths[3]).exists():
        pdf.insert_chart(chart_paths[3], w=140, caption="News sentiment gauge and breakdown")

    # Top headlines table
    articles = news_data.get("articles", [])[:8]
    if articles:
        pdf.section_title("Recent Headlines", color=(0, 160, 120))
        for i, art in enumerate(articles):
            bg = (248, 246, 255) if i % 2 == 0 else (255, 255, 255)
            pdf.set_fill_color(*bg)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(40, 40, 70)
            title = art["title"][:90] + ("…" if len(art["title"]) > 90 else "")
            pdf.cell(130, 6, f"  {pdf._clean(title)}", fill=True)
            sent = art.get("sentiment_label", "Neutral")
            if "Positive" in sent:
                pdf.set_text_color(22, 163, 74)
            elif "Negative" in sent:
                pdf.set_text_color(220, 38, 38)
            else:
                pdf.set_text_color(100, 100, 120)
            pdf.cell(30, 6, pdf._clean(sent), fill=True, align="C")
            pdf.set_text_color(120, 120, 140)
            pdf.cell(0, 6, pdf._clean(art.get("published", "")[:10]), fill=True, align="R")
            pdf.ln(6)


def _page_recommendation(pdf, report_data, stock_data, analysis_data):
    pdf.section_title("Investment Recommendation & Risk Analysis")

    rec = report_data.get("recommendation", "HOLD")
    conf = report_data.get("confidence_score", 50)
    target = report_data.get("target_price")
    current = stock_data.get("current_price", 0)

    # Badge
    pdf.ln(4)
    pdf.rec_badge(rec)
    if target and current:
        upside = ((float(target) - float(current)) / float(current)) * 100
        pdf.set_x(80)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(50, 50, 80)
        pdf.cell(0, 14,
                 f"  12-Month Target: ${target}  |  "
                 f"Upside/Downside: {upside:+.1f}%  |  "
                 f"Confidence: {conf:.0f}%")
    pdf.ln(12)

    rationale = report_data.get("recommendation_rationale", "")
    if rationale:
        pdf.body_text(rationale)

    pdf.section_title("Data Analysis", color=(0, 160, 120))
    pdf.body_text(report_data.get("data_analysis_section", ""))

    risks = report_data.get("risk_factors", [])
    catalysts = report_data.get("catalysts", [])

    if risks:
        pdf.section_title("Risk Factors", color=(220, 38, 38))
        for r in risks:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(60, 60, 80)
            pdf.cell(5, 6, "o")
            pdf.cell(0, 6, pdf._clean(r), ln=True)
        pdf.ln(2)

    if catalysts:
        pdf.section_title("Potential Catalysts", color=(22, 163, 74))
        for c in catalysts:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(60, 60, 80)
            pdf.cell(5, 6, "o")
            pdf.cell(0, 6, pdf._clean(c), ln=True)


def _page_agent_log(pdf, messages):
    pdf.section_title("AI Agent Conversation Log")
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 120)
    pdf.cell(0, 5, "This section shows how the AI agents collaborated to produce this report.", ln=True)
    pdf.ln(3)

    agent_colors = {
        "Market Researcher": (108, 62, 244),
        "Data Analyst":      (0, 160, 120),
        "Report Writer":     (220, 120, 0),
    }

    for msg in messages:
        agent = msg.get("agent", "System")
        content = msg.get("content", "")
        ts = msg.get("timestamp", "")
        color = agent_colors.get(agent, (80, 80, 100))

        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(*color)
        agent_header = pdf._clean(f"[{ts}] {agent}")
        pdf.cell(35, 5, agent_header)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(60, 60, 80)
        # Clean content and multi_cell
        pdf.multi_cell(0, 5, pdf._clean(content))
        pdf.ln(1)

        if pdf.get_y() > 265:
            pdf.add_page()
            pdf.section_title("AI Agent Conversation Log (continued)")


# ─── LangGraph node ───────────────────────────────────────────────────────────
def _log_msg(state, content, status="running"):
    msgs = list(state.get("messages", []))
    msgs.append(AgentMessage(
        agent="PDF Generator",
        content=content,
        timestamp=datetime.now().strftime("%H:%M:%S"),
        status=status,
    ))
    return msgs


def pdf_generator_node(state: FinancialAgentState) -> FinancialAgentState:
    msgs = _log_msg(state, "📄 Generating professional PDF report…")
    errors = list(state.get("errors", []))

    try:
        pdf_path = generate_pdf(state)
        report_data = dict(state.get("report_data") or {})
        report_data["pdf_path"] = pdf_path
        msgs = _log_msg({**state, "messages": msgs},
                        f"✅ PDF report saved to: {pdf_path}", "done")
        return {
            **state,
            "report_data": report_data,
            "messages": msgs,
            "errors": errors,
            "current_agent": "done",
            "completed": True,
        }
    except Exception as e:
        errors.append(f"PDF generation error: {e}")
        msgs = _log_msg({**state, "messages": msgs}, f"⚠️ PDF error: {e}", "error")
        logger.error(f"PDF generation failed: {e}")
        return {
            **state,
            "messages": msgs,
            "errors": errors,
            "current_agent": "done",
            "completed": True,
        }
